# Generated by Django 4.1.7 on 2023-06-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='users/Y%/m%/', verbose_name='Foto de perfil'),
        ),
    ]
