# Generated by Django 4.2.1 on 2023-06-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graficas',
            name='nucleos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
