# Generated by Django 4.2.1 on 2023-06-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_graficas_nucleos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procesadores',
            old_name='ghz',
            new_name='mhz',
        ),
    ]
