# Generated by Django 4.2.1 on 2023-06-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_rename_ghz_procesadores_mhz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesadores',
            name='mhz',
            field=models.IntegerField(),
        ),
    ]
