# Generated by Django 4.2.1 on 2023-06-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0005_alter_procesadores_mhz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesadores',
            name='hilos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesadores',
            name='mhz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesadores',
            name='nucleos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
