# Generated by Django 4.1.7 on 2023-06-07 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefonos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rams',
            name='velocidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.ramsvelocidades'),
        ),
        migrations.AddField(
            model_name='historiales',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graficas',
            name='gb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.graficasgb'),
        ),
        migrations.AddField(
            model_name='graficas',
            name='velocidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.graficasvelocidades'),
        ),
        migrations.AddField(
            model_name='favoritos_urljuegos',
            name='favorito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.favoritos'),
        ),
        migrations.AddField(
            model_name='favoritos_urljuegos',
            name='urlJuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.urljuegos'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='grafica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.graficas'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='procesador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.procesadores'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.rams'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='sistemaOperativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.sistemasoperativos'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
